### ISSUE TITLE
Start page form

### ISSUE THREAD

**Issue by fastyep** [LISENKOSOFT/SapReader#2]
Need to write form for SapReader start page. Must include:
- About
- Sapphire about
- Authors
- How to start
- Adds

**Comment by fastyep** [comment]
Link to download SapReaderFormer
https://github.com/LISENKOSOFT/SapReaderFormer/blob/master/bin/Debug/SapReaderFormer.exe

**Comment by DenisNovac** [comment]
<FORM name="LIENKO SOFT security lite" author="LIENKO SOFT"> 
<label location="12,12" font="18">SapReader</label> 
<button location="12,50" click="clickStart:">Начало работы</button> 
<button location="112,50" click="clickAbout:">О программе</button> 
<button location="203,50" click="clickSap:">О Sapphire™</button> 

<label location="12,80" name="mainLabel">Добро пожаловать в SapReader.</label>
<labelStart>Для начала работы воспользуйтесь формой ниже или используйте меню в верхней части программы.</labelStart>
<labelAbout>Программа предназначена для работы в двух режимах: проводник с возможностью шифровать файлы и архиватор зашифрованных архивов.</labelAbout>
<labelSap>Security Algorythm, Private Protection From InfoRmation Exposure (Sapphire™) Защитный алгоритм, частная защита от уязвимости 
информации - криптографический алгоритм с закрытым ключом для хранения и компакной передачи информации.</labelSap>


<textbox location="12,117" size="420,20" name="key">Введите ключ</textbox> 
<richtextbox location="12,139" size="420,134" name="text">Введите текст</richtextbox> 
<button location="12,275" click="Click:">Шифровать</button> 
<button location="100,275" click="@Click:">Расшифровать</button> 



<label location="12,300" font="7">SapphireReader powered by Sapphire™
LISENKO SOFT 2016 год
</label>





<script> 
clickStart:
#mainLabel=#labelStart;
clickAbout:
#mainLabel=#labelAbout;
clickSap:
#mainLabel=#labelSap;

Click: 
$var = Click(@) 
Compare($var,false) 
#text=Sapphire(#text,#key) 
!#text=@Sapphire(#text,#key); 


</script> 

</FORM>

**Comment by DenisNovac** [comment]
`
<FORM name="LIENKO SOFT security lite" author="LIENKO SOFT"> 
<label location="12,12" font="18">SapReader</label> 
<button location="12,50" click="clickStart:">Начало работы</button> 
<button location="112,50" click="clickAbout:">О программе</button> 
<button location="203,50" click="clickSap:">О Sapphire™</button> 

<label location="12,80" name="mainLabel">Добро пожаловать в SapReader.</label>
<labelStart>Для начала работы воспользуйтесь формой ниже или используйте меню в верхней части программы.</labelStart>
<labelAbout>Программа предназначена для работы в двух режимах: проводник с возможностью шифровать файлы и архиватор зашифрованных архивов.</labelAbout>
<labelSap>Security Algorythm, Private Protection From InfoRmation Exposure (Sapphire™) Защитный алгоритм, частная защита от уязвимости 
информации - криптографический алгоритм с закрытым ключом для хранения и компакной передачи информации.</labelSap>


<textbox location="12,117" size="420,20" name="key">Введите ключ</textbox> 
<richtextbox location="12,139" size="420,134" name="text">Введите текст</richtextbox> 
<button location="12,275" click="Click:">Шифровать</button> 
<button location="100,275" click="@Click:">Расшифровать</button> 



<label location="12,300" font="7">SapphireReader powered by Sapphire™
LISENKO SOFT 2016 год
</label>





<script> 
clickStart:
#mainLabel=#labelStart;
clickAbout:
#mainLabel=#labelAbout;
clickSap:
#mainLabel=#labelSap;

Click: 
$var = Click(@) 
Compare($var,false) 
#text=Sapphire(#text,#key) 
!#text=@Sapphire(#text,#key); 


</script> 

</FORM>
`

**Comment by DenisNovac** [comment]
```
<FORM name="LIENKO SOFT security lite" author="LIENKO SOFT"> 
<label location="12,12" font="18">SapReader</label> 
<button location="12,50" click="clickStart:">Начало работы</button> 
<button location="112,50" click="clickAbout:">О программе</button> 
<button location="203,50" click="clickSap:">О Sapphire™</button> 

<label location="12,80" name="mainLabel">Добро пожаловать в SapReader.</label>
<labelStart>Для начала работы воспользуйтесь формой ниже или используйте меню в верхней части программы.</labelStart>
<labelAbout>Программа предназначена для работы в двух режимах: проводник с возможностью шифровать файлы и архиватор зашифрованных архивов.</labelAbout>
<labelSap>Security Algorythm, Private Protection From InfoRmation Exposure (Sapphire™) Защитный алгоритм, частная защита от уязвимости 
информации - криптографический алгоритм с закрытым ключом для хранения и компакной передачи информации.</labelSap>


<textbox location="12,117" size="420,20" name="key">Введите ключ</textbox> 
<richtextbox location="12,139" size="420,134" name="text">Введите текст</richtextbox> 
<button location="12,275" click="Click:">Шифровать</button> 
<button location="100,275" click="@Click:">Расшифровать</button> 



<label location="12,300" font="7">SapphireReader powered by Sapphire™
LISENKO SOFT 2016 год
</label>





<script> 
clickStart:
#mainLabel=#labelStart;
clickAbout:
#mainLabel=#labelAbout;
clickSap:
#mainLabel=#labelSap;

Click: 
$var = Click(@) 
Compare($var,false) 
#text=Sapphire(#text,#key) 
!#text=@Sapphire(#text,#key); 


</script> 

</FORM>
```
